# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_reviewassignment_display_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='for_author_consumption',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='visibility',
            field=models.CharField(choices=[('blind', 'Single Anonymous')], default='double-blind', max_length=20, verbose_name='Anonymity'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
