# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20230504_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiondraft',
            name='revision_request_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
