# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        RevisionRequest = apps.get_model('review', 'RevisionRequest')
        for revision_request in RevisionRequest.objects.all():
            article = revision_request.article
            revision_request.old_title = article.title
            revision_request.old_abstract = article.abstract
            revision_request.revised_title = article.title
            revision_request.revised_abstract = article.abstract
            revision_request.save()

    reverse_func = migrations.RunPython.noop

    dependencies = [
        ('review', '0019_auto_20230504_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='old_abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='old_title',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='revised_abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='revised_title',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
    ]
