# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        ReviewAssignment = apps.get_model("review", "ReviewAssignment")
        for assignment in ReviewAssignment.objects.all():
            assignment.display_review_file = True
            assignment.save()

    dependencies = [
        ('review', '0020_auto_20230507_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='display_review_file',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
