# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-12 14:23
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations

secondary_author_submission_acknowledgement = """
<p>Dear {{ author.full_name }},</p>

<p>You have been listed as an author on {{ article.title }}, submitted to Imaging Neuroscience.</p>

<p>You do not need to take any action if you are in agreement to be listed; all further communication will be via the submitting author. </p>

<p>If you did not already have an account on the interim Imaging Neuroscience website, one will have been partially created for you as part of the submission process for this new paper. If you would like to access this account fully in future (e.g., to submit your own paper, or to act as a reviewer), please go to the <a href="{{ journal.site_url }}">submission website</a>, click <em>Log in</em>, enter your email address, and click <em>Reset password</em> to set a password up for the first time.</p>

<p>Regards,</p>
""".strip().replace('\n', '')

subject_secondary_author_submission_acknowledgement = """
Article Submission
""".strip().replace('\n', '')


class Migration(migrations.Migration):


    def forwards_func(apps, schema_editor):
        Setting = apps.get_model("core", "Setting")
        SettingValue = apps.get_model("core", "SettingValue")
        SettingGroup = apps.get_model("core", "SettingGroup")
        call_command('load_default_settings')

        def add_setting(key, value, pretty_name, description, stype, group):
            setting, c = Setting.objects.get_or_create(
                name=key,
                types=stype,
                group=SettingGroup.objects.filter(name=group)[0],
                is_translatable=True,
                pretty_name=pretty_name,
                description=description,
            )

            setting_value, _ = SettingValue.objects.get_or_create(
                journal=None,
                setting=setting,
            )
            setting_value.value = value
            setting_value.save()

        add_setting(
            'secondary_author_submission_acknowledgement',
            secondary_author_submission_acknowledgement,
            'Secondary Author Submission Acknowledgement',
            'Email sent to secondary authors when an article is submitted.',
            'rich-text',
            'email',
        )
        add_setting(
            'subject_secondary_author_submission_acknowledgement',
            subject_secondary_author_submission_acknowledgement,
            'Secondary Author Submission Acknowledgement',
            'Subject line for email sent to secondary authors when an article is submitted.',
            'text',
            'email_subject',
        )


    reverse_func = migrations.RunPython.noop

    dependencies = [
        ('journal', '0059_auto_20230505_1341'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
    ]
