# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Country = apps.get_model("core", "Country")
        country = Country.objects.get(code='TW')
        country.name = 'Taiwan'
        country.save()

    def reverse_func(apps, schema_editor):
        Country = apps.get_model("core", "Country")
        country = Country.objects.get(code='TW')
        country.name = 'Taiwan, Province of China'
        country.save()

    dependencies = [
        ('core', '0079_auto_20230208_1233'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
